services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - ./postgres_data:${PG_DATA}
    ports:
      - "${PG_PORT}:5432"
    restart: unless-stopped
    networks:
      - network_app

networks:
  network_app:
    driver: bridge