services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - ./postgres_data:${PG_DATA}
    ports:
      - "${PG_PORT}:5432"
    restart: unless-stopped
    networks:
      - network_app

  api:
    build: .
    container_name: api
    command: >
      sh -c "alembic upgrade head &&
             python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
#    ports:
#      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - network_app

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"  # Публикуем порт наружу
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Конфиг Nginx
    networks:
      - network_app


networks:
  network_app:
    driver: bridge