[tool.ruff]

# Пути, в которых будет проверка
src = ["src", "tests"]
preview = true

# Исключаемые папки
exclude = ["venv", "postgres_data", "redis_data", "plugin"]

# Максимальная длина строки согласно PEP 8 (79 символов)
line-length = 79

[tool.ruff.lint]
# Включаем основные группы правил
select = [
    "E",   # PEP 8 ошибки
    "W",   # PEP 8 предупреждения
    "F",   # Pyflakes
    "I",   # isort (сортировка импортов)
    "N",   # pep8-naming
    "UP",  # pyupgrade (современный синтаксис)
    "I001",
]


[tool.ruff.lint.isort]
#Указывает что принадлежит к "first-party"
known-first-party = ["src", "tests"]

# Последовательность групп импортов
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]

# Вставлять одну пустую строку между группами импортов
lines-between-types = 1

# Не принудительно сортировать внутри секций, оставить дефолтное поведение
force-sort-within-sections = false

# Отключаем отключение разделения по секциям
no-sections = false

[tool.ruff.format]
line-ending = "auto"
# Форматируем докстринги, длина строки в них согласно PEP 8
docstring-code-format = true
docstring-code-line-length = 72

