[tool.ruff]
src = ["src", "tests"]
exclude = ["venv", "postgres_data", "redis_data"]
line-length = 79

[tool.ruff.lint]
select = [
    "E",   # PEP 8 ошибки (E)
    "W",   # PEP 8 предупреждения (W)
    "F",   # Pyflakes
    "I",   # isort (сортировка импортов)
#    "B",   # flake8-bugbear
#    "C",   # flake8-comprehensions
    "N",   # pep8-naming
    "UP",  # pyupgrade (современный синтаксис)
#    "YTT", # flake8-2020 (устаревшие фичи)
]

[tool.ruff.lint.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]
force-sort-within-sections = false

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 72